version: '3.8'
services:
  frontend:
    image: devops-static-web/frontend
    container_name: frontend
    build:
      context: ./frontend/.
      dockerfile: ../Dockerfile
      args:
        PORT: 3000
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - PRODUCTS_SERVICE=products
      - SHOPPING_CART_SERVICE=shopping-cart
      - MERCHANDISE_SERVICE=merchandise
    
  shopping-cart:
    image: devops-static-web/shopping-cart
    container_name: shopping-cart
    build:
      context: ./shopping-cart/.
      dockerfile: ../Dockerfile
      args:
        PORT: 3002
    environment:
      - PORT=3002

  merchandise:
    image: devops-static-web/merchandise
    container_name: merchandise
    build:
      context: ./merchandise/.
      dockerfile: ../Dockerfile
      args:
        PORT: 3003
    environment:
      - PORT=3003
  products:
    image: devops-static-web/products
    container_name: products
    build:
      context: ./products/.
      dockerfile: ../Dockerfile
      args:
        PORT: 3001
    environment:
      - PORT=3001
